#!/bin/bash
# mac compile
# clang -std=c++11 main.cpp  gl_frontEnd.cpp -lm -lstdc++ -framework OpenGl -framework GLUT -lpthread -o travel

# linux compile
g++ main.cpp  gl_frontEnd.cpp -lm -lGL -lglut -lpthread -o travel

./travel